#!/usr/bin/env python3.5
# coding = utf-8

import argparse
import os
from src.Classes.Controller import Controller
from src.Classes.Client import Client
from src import config


def parse_arg():
    parser = argparse.ArgumentParser(
        usage="USAGE: ./zappy_ai -p port -n name -h machine", add_help=False)
    parser.add_argument("-help", action="store_true")
    parser.add_argument("-p", help="is the port number", required=True,
                        type=int)
    parser.add_argument("-n", help="is the name of the team", required=True)
    parser.add_argument("-h",
                        help="is the name of the machine; localhost by default",
                        default="localhost")

    args = parser.parse_args()
    if args.help:
        exit("""USAGE: ./zappy_ai -p port -n name -h machine
    port    is the port number
    name    is the name of the team
    machine is the name of the machine; localhost by default""")
    config.file_name = os.path.realpath(__file__)
    config.hostname = args.h
    config.port = args.p
    config.team_name = args.n
    return args


def run(args):
    with Client(args.h, args.p) as (client, error):
        if error:
            exit(error)
        client.poll()
        # ai = AIController(client, args.n)
        # print(ai.ulapid)
        # print(ai.broadcast("test"))
        # print(client.read_line())


def main():
    args = parse_arg()
    try:
        run(args)
    except Exception as e:
        exit("Fatal Error: %s" % e)


if __name__ == "__main__":
    main()
